# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 152415837+SamikshaSolanke@users.noreply.github.com
author_name: Samiksha Solanke
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: first_algo

